type Side_Projects = {
  title: string;
  description: string;
  href: string;
  github?: string;
  image: string;
  tags: string[];
  featured?: boolean;
};

export const NAVIGATION = [
  {
    title: "Home",
    href: "/",
  },
  {
    title: "Projects",
    href: "/projects",
  },
  {
    title: "Blog",
    href: "/blog",
  },
  {
    title: "Board",
    href: "/board",
  },
  {
    title: "About",
    href: "/about",
  },
  //contact is included in the navigation by contact-form.tsx
];

export const SIDE_PROJECTS: Side_Projects[] = [
  {
    title: "Indeed WebScraper using Selenium",
    description:
      "I created a webscraper 🕸️ tool to fetch indeed data. It will return job title, company name, job id, url of the job, salary(if present) and whole description of respective job.",
    href: "https://github.com/invictusaman/Indeed-WebScraper",
    github: "https://github.com/invictusaman/Indeed-WebScraper",
    image: "/projects/side_projects/indeedscraper.webp",
    tags: ["WebScraper", "Python"],
  },
  {
    title: "Glassdoor WebScraper",
    description:
      "I designed a scraping 🕸️ tool to extract job posting data from Glassdoor. This scraping tool will return job title, company name, job id, location, salary, language and skills and many more.",
    href: "https://github.com/invictusaman/Glassdoor-WebScraper",
    github: "https://github.com/invictusaman/Glassdoor-WebScraper",
    image: "/projects/side_projects/glassdoorscraper.webp",
    tags: ["WebScraper", "Python"],
  },
  {
    title: "Data Analyst Jobs Dataset",
    description:
      "This dataset was generated by extracting real-time job postings for Data Analyst roles in Canada from popular job search platforms Indeed and Glassdoor.",
    href: "https://www.kaggle.com/datasets/amanbhattarai695/data-analyst-job-roles-in-canada",
    image: "/projects/side_projects/dataset_kaggle.webp",
    tags: ["Dataset"],
  },
  {
    title: "Practicing Advanced SQL Queries",
    description:
      "This project highlights my SQL problem solving skills on advanced concepts like views, stored procedure, ACID transaction and Joins.",
    href: "https://github.com/invictusaman/Advanced_Sql_Queries_On_Chicago_Dataset",
    github: "https://github.com/invictusaman/Advanced_Sql_Queries_On_Chicago_Dataset",
    image: "/projects/side_projects/Advanced-SQL.webp",
    tags: ["SQL", "Data Querying"],
  },
];

export const TECH_STACK = [
  {
    title: "Python",
    href: "https://python.org/",
  },
  {
    title: "SQL",
    href: "https://en.wikipedia.org/wiki/SQL",
  },
  {
    title: "Tableau",
    href: "https://tableau.com/",
  },
  {
    title: "Excel",
    href: "https://www.microsoft.com/en-ca/microsoft-365/excel",
  },
  {
    title: "Pandas",
    href: "https://pandas.pydata.org/",
  },
  {
    title: "Numpy",
    href: "https://numpy.org/",
  },
  {
    title: "Matplotlib",
    href: "https://matplotlib.org/",
  },
  {
    title: "Seaborn",
    href: "https://seaborn.pydata.org/",
  },
  {
    title: "Jupyter Notebook",
    href: "https://jupyter.org/",
  },
  {
    title: "Next JS",
    href: "https://nextjs.org/",
  },
  {
    title: "Tailwind CSS",
    href: "https://tailwindcss.com",
  },
  {
    title: "Blogger",
    href: "https://blogger.com",
  },
  {
    title: "Framer Motion",
    href: "https://www.framer.com/motion",
  },
  {
    title: "HTML5",
    href: "https://en.wikipedia.org/wiki/HTML5",
  },
  {
    title: "Javascript",
    href: "https://www.javascript.com/",
  },
];
