type Side_Projects = {
  title: string;
  description: string;
  href: string;
  github?: string;
  image: string;
  tags: string[];
  featured?: boolean;
};

export const NAVIGATION = [
  {
    title: "Home",
    href: "/",
  },
  {
    title: "Projects",
    href: "/projects",
  },
  {
    title: "Blog",
    href: "/blog",
  },
  //{
  //  title: "Board",
  //  href: "/board",
  //},
  {
    title: "About",
    href: "/about",
  },
  //contact is included in the navigation by contact-form.tsx
];

export const SIDE_PROJECTS: Side_Projects[] = [
  {
    title: "Indeed WebScraper using Selenium",
    description:
      "I created a webscraper 🕸️ tool to fetch indeed data. It will return job title, company name, job id, url of the job, salary(if present) and whole description of respective job.",
    href: "https://github.com/invictusaman/Indeed-WebScraper",
    github: "https://github.com/invictusaman/Indeed-WebScraper",
    image: "/projects/side_projects/indeedscraper.webp",
    tags: ["WebScraper", "Python"],
  },
  {
    title: "Glassdoor WebScraper",
    description:
      "I designed a scraping 🕸️ tool to extract job posting data from Glassdoor. This scraping tool will return job title, company name, job id, location, salary, language and skills and many more.",
    href: "https://github.com/invictusaman/Glassdoor-WebScraper",
    github: "https://github.com/invictusaman/Glassdoor-WebScraper",
    image: "/projects/side_projects/glassdoorscraper.webp",
    tags: ["WebScraper", "Python"],
  },
  {
    title: "Data Analyst Jobs Dataset",
    description:
      "This dataset was generated by extracting real-time job postings for Data Analyst roles in Canada from popular job search platforms Indeed and Glassdoor.",
    href: "https://www.kaggle.com/datasets/amanbhattarai695/data-analyst-job-roles-in-canada",
    image: "/projects/side_projects/dataset_kaggle.webp",
    tags: ["Dataset"],
  },
  {
    title: "Practicing Advanced SQL Queries",
    description:
      "This project highlights my SQL problem solving skills on advanced concepts like views, stored procedure, ACID transaction and Joins.",
    href: "https://github.com/invictusaman/Advanced_Sql_Queries_On_Chicago_Dataset",
    github:
      "https://github.com/invictusaman/Advanced_Sql_Queries_On_Chicago_Dataset",
    image: "/projects/side_projects/Advanced-SQL.webp",
    tags: ["SQL", "Data Querying"],
  },
];

export const TECH_STACK = [
  {
    title: "Azure",
    href: "https://azure.microsoft.com/",
  },
  {
    title: "AWS",
    href: "https://aws.amazon.com/",
  },
  {
    title: "Databricks",
    href: "https://www.databricks.com/",
  },
  {
    title: "Apache Spark",
    href: "https://spark.apache.org/",
  },
  {
    title: "Snowflake",
    href: "https://www.snowflake.com/",
  },
  {
    title: "Python",
    href: "https://www.python.org/",
  },
  {
    title: "SQL",
    href: "https://en.wikipedia.org/wiki/SQL",
  },
  {
    title: "Airflow",
    href: "https://airflow.apache.org/",
  },
  {
    title: "Delta Lake",
    href: "https://delta.io/",
  },
  {
    title: "Hadoop",
    href: "https://hadoop.apache.org/",
  },
  {
    title: "Hive",
    href: "https://hive.apache.org/",
  },
  {
    title: "Azure Data Factory",
    href: "https://azure.microsoft.com/en-us/products/data-factory/",
  },
  {
    title: "ADLS Gen2",
    href: "https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-introduction",
  },
  {
    title: "AWS S3",
    href: "https://aws.amazon.com/s3/",
  },
  {
    title: "AWS Glue",
    href: "https://aws.amazon.com/glue/",
  },
  {
    title: "Tableau",
    href: "https://www.tableau.com/",
  },
  {
    title: "Git",
    href: "https://git-scm.com/",
  },
];
